---
dist: trusty
language: node_js
node_js:
  - 9
cache:
  directories:
  - node_modules
install: true
deploy:
  provider: npm
  email: "navit@nav.no"
  api_key: $NPM_TOKEN
  on:
    tags: true
  skip_cleanup: true
